nome = input("Bom Dia! Por favor Digite seu nome completo: ")
numero_de_telefone = int(input("Por favor coloque seu telefone: "))
estado = input("Por favor insira seu estado: ")
cpf = int(input("Por favor Digite seu CPF: "))
senha = input("Por favor crie uma senha: ")
print(f"\nBom dia", nome,"Bem vindo ao nosso serviço")
print(f"Seu telefone é", numero_de_telefone)
print(f"Seu estado é", estado)
print(f"Seu CPF é", cpf,)
print(f"Sua senha é", senha)
print(f"todas essas informações serão bem guardadas em nosso banco de dados, tenha um bom uso", nome)